### ISSUE TITLE
delete_instance hook doesn't work.

### ISSUE THREAD

**Issue by itwesley** [larsks/demo_nova_hooks#2]
I try to use your hooks sample, create instance hook work fine(hook-create.log was created), but delete instance hook doesn't write  hook-delete.log when I terminate a instance.

**Comment by msolberg** [comment]
What version of OpenStack?  Are the nova-api and nova-compute services running on the same system?

**Comment by msolberg** [comment]
What version of OpenStack?
Are nova-api and nova-compute running on the same machine?

**Comment by itwesley** [comment]
My openstack version is Juno. Nova-api was installed on controller node, and nova-compute was installed on another compute node. (multi-host)

**Comment by itwesley** [comment]
Hi msolberg, I saw you sending a pull request on this repository. Does any hook methods(create, delete, network) not work fine when you run it?

**Comment by msolberg** [comment]
They do work in my environment, but I can verify against a clean Juno install for you.  One thing to note is that the create hook runs via nova-api while the delete hook and network hook run via nova-compute.  Those logs will be created on the compute hosts in a multi-host install.

**Comment by itwesley** [comment]
First, thanks for your reply, I got it. So all of my compute nodes need to install the repository, and then I need to check host-delete.log on my compute node when I terminate instances, right? : )

**Comment by itwesley** [comment]
Hi msolberg, I test it successfully. You do me a solid favor, I really apprecaite your help. :+1:
